### ISSUE TITLE
Would you mind sharing the results when you ran the benchmark?

### ISSUE THREAD

**Issue by shafqatevo** [michaeltelford/cold_start_benchmarker#1]
Hi @michaeltelford, thanks for sharing this work!

Do you by any chance have the data of your runs or can remember the ballpark of the typical cold start time to expect?

**Comment by michaeltelford** [comment]
Hi @shafqatevo! I checked but cannot find the benchmark results unfortunately. Apologies. I do remember that the `go` start was the fastest (as expected, given that it's starting a binary instead of interpreting code). I don't think there was much difference between `python` and `node` for projects of this size (tiny hello world apps) but this would certainly give clearer results with real world projects e.g. starting a web server. Hope that helps! :+1:
